kind: pipeline
name: default

steps:
- name: install and run scripts
  image: python:3
  commands:
  - git fetch --tags
  - pip install Cython
  - python setup.py install

- name: generate sdist
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: notify
  when:
    status:
    - failure 
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
