kind: pipeline
name: default

steps:
- name: install
  image: python:3
  commands:
  - git fetch --tags
  - pip install Cython
  - python setup.py install

- name: develop
  image: python:3
  commands:
  - git fetch --tags
  - pip install Cython
  - python setup.py develop

- name: sdist
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: compile windows
  image: dockcross/windows-static-x64
  commands:
  - apt install -y python3-pip python3-dev
  - pip3 install Cython 
  - python3 compile.py build_ext --exp_month=7 --exp_year=2019 --macs=2234420019928

- name: upload sdist
  image: appleboy/drone-scp
  settings:
    host: austerlitz.dessia.tech
    target: /home/drone/autobuild/mechanical_components/
    source: dist/*.tar.gz
    strip_components: 1
    username: drone
    password:
      from_secret: ssh_drone_password

