kind: pipeline
name: default

steps:

       
- name: install, doc and script running
  image: python:3
  commands:
  - git clone https://git.dessia.tech/DessIA/dessia-common.git
  - cd dessia-common
  - python setup.py install
  - cd ..
  - git fetch --tags
  - pip install Cython
  - python setup.py install
  - pip install sphinx sphinx_rtd_theme
  - cd doc
  - make html
  - cd ../
  - python scripts/bearings/bearing3.py
  - python scripts/meshes/meshes_agb.py
  - python scripts/meshes/meshes2.py

- name: develop
  image: python:3
  commands:
  - cd dessia-common
  - python setup.py develop
  - cd ..
  - git fetch --tags
  - pip install Cython
  - python setup.py develop

- name: sdist
  image: python:3
  commands:
  - git fetch --tags
  - python setup.py sdist --formats=gztar,zip

- name: push opensource from sdist
  image: alpine/git
  when:
    branch: 
      - master
  commands:
    - git clone https://git.dessia.tech/OpenSource/MechanicalComponents.git git-opensource
    - tar -vxf dist/*.tar.gz --strip-components=1 -C git-opensource
    - cd git-opensource
    - git config --global user.email "root@dessia.tech"
    - git config --global user.name "Root commit bot" 
    - git add -A
    - if ! [[ -z $(git status -s -uno) ]]; then git commit -m "Automated commit"; fi
    - git push origin master


- name: upload sdist to seafile
  image: dessia/drone-seafile
  when: 
    branch: 
      - master
  settings:
    server_url: https://partage.dessia.tech
    repo_id:
      from_secret: seafile_repo_id
    seafile_token:
      from_secret: seafile_token
    files: dist/*
    root_directory: /mechanical_components/


- name: install from sdist and run test scripts
  image: python:3
  commands:
  - pip install Cython
  - cd dessia-common
  - python setup.py install
  - cd ..
  - mkdir install_from_sdist
  - tar -xf dist/*.tar.gz -C install_from_sdist/
  - cd install_from_sdist
  - cd mechanical_components*
  - python setup.py install


- name: compile linux
  image: python:3
  commands:
  - pip install Cython
  - python compile.py build_ext --exp_month=7 --exp_year=2029 --macs=2234420019928

- name: upload_doc_master
  image: appleboy/drone-scp
  when: 
    branch: 
      - master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/MechanicalComponents/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password
- name: notify
  when:
    status:
    - failure 
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
