kind: pipeline
name: default

steps:
- name: install, doc and script running
  image: python:3.8
  commands:
  - pip install Cython
  - git fetch --tags
  - python setup.py install
  - pip install sphinx sphinx_rtd_theme
  - cd doc
  - make html
  - cd ../
  - python scripts/bearings/bearing_test.py
  - python scripts/bearings/optimizer_bearing_test.py
  # - python scripts/bearings/workflow_assembly_bearing_test.py
  # - python scripts/bearings/workflow_combination_bearing_test.py

- name: develop
  image: python:3.8
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist
  image: python:3.8
  commands:
  - python setup.py sdist

- name: compile linux test licence valid
  image: python:3.9
  commands:
  - pip install Cython
  - python compile.py cdist_wheel --exp-month=7 --exp-year=2029
  - pip install client_dist/*.whl
  - python scripts/compilation_test.py test_valid_license

- name: compile linux test licence unvalid
  image: python:3.9
  commands:
  - pip install Cython
  - python compile.py cdist_wheel --exp-month=7 --exp-year=2020
  - pip install client_dist/*.whl
  - python scripts/compilation_test.py test_unvalid_license

- name: push opensource from sdist
  image: alpine/git
  when:
    branch: master
    event: push
  commands:
    - git clone https://gitea.dessia.tech/OpenSource/MechanicalComponents.git git-opensource
    - cd git-opensource
    - git branch from_proprietary
    - git checkout from_proprietary
    - git pull origin from_proprietary
    - tar -vxf ../dist/*.tar.gz --strip-components=1 -C .
    - git config --global user.email "root@dessia.tech"
    - git config --global user.name "Root commit bot"
    - git add -A
    - if ! [[ -z $(git status -s -uno) ]]; then git commit -m "Automated commit"; fi
    - git push origin from_proprietary

- name: copy tag to opensource
  image: alpine/git
  when:
    event:
    - tag
  commands:
  - git clone https://gitea.dessia.tech/OpenSource/MechanicalComponents.git git-opensource
  - cd git-opensource
  - git branch from_proprietary
  - git checkout from_proprietary
  - git pull origin from_proprietary
  - git config --global user.email "root@dessia.tech"
  - git config --global user.name "Root commit bot"
  - git tag -a ${DRONE_TAG} -m ${DRONE_TAG}
  - git push origin --tags



- name: upload_doc_master
  image: appleboy/drone-scp
  when:
    branch: master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/MechanicalComponents/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password


- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
